"0","df %>% "
"0","  filter(p == 55, q == 55, sig == 0.5) %>% "
"0","  select(K, n, p, q, X_rmse, Y_rmse) %>% "
"0","  group_by(K, n) %>% "
"0","  summarise(median = median(X_r2), "
"0","            Q1 = quantile(X_r2, 1/4),"
"0","            Q3 = quantile(X_r2, 3/4),"
"0","            .groups = ""drop"") %>% "
"0","  ggplot(aes(x = K, y = median, col = as.factor(n))) +"
"0","  geom_linerange(aes(ymin = Q1, ymax = Q3), position = position_dodge(width = 0.5)) +"
"0","  geom_point(position = position_dodge(width = 0.5)) +"
"0","  harrypotter::scale_color_hp_d(""ravenclaw"") +"
"0","  theme_classic() +"
"0","  labs(x=  ""K"", y = ""R2 (P)"", colour = ""Predictor dimension:"") +"
"0","  theme(legend.position = ""bottom"","
"0","        text = element_text(size = 20)) +"
"0","  guides(colour = guide_legend(ncol = 2))"
"1","[1m[33mError[39m in [38;5;232m`summarise()`[39m:[22m
[38;5;232m[33m![38;5;232m Problem while computing `median = median(X_r2)`.
[36mâ„¹[38;5;232m The error occurred in group 1: K = 1, n = 10.[39m
[1mCaused by error in [38;5;232m`median()`[39m:[22m
[33m![39m object 'X_r2' not found
Backtrace:
[90m  1. [39m... %>% ggplot(aes(x = K, y = median, col = as.factor(n)))
[90m 11. [39m[1mstats[22m::median(X_r2)
"
